name: PHP Code Style

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code_style:
    name: PHP Code Style ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-php${{ matrix.php-versions }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-php${{ matrix.php-versions }}-
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: |
          composer validate
          composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run style check
        run: |
          php vendor/bin/php-cs-fixer fix --dry-run --diff
